# Generated by Django 4.2.2 on 2023-11-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_storemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinmodel',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.storemodel'),
        ),
    ]
